import type {Pool} from 'pg';

export const workerObservationCodes=['INBOX','OUTBOX','AI','INCIDENT'] as const;
export type WorkerObservationCode=typeof workerObservationCodes[number];
export interface WorkerObserverOptions {now?:()=>number}

function isWorkerObservationCode(value:unknown):value is WorkerObservationCode{
 return typeof value==='string'&&(workerObservationCodes as readonly string[]).includes(value);
}

/** Store only the fixed worker code and a timestamp generated by PostgreSQL. */
export async function recordWorkerObservation(pool:Pool,worker:WorkerObservationCode):Promise<void>{
 if(!isWorkerObservationCode(worker))throw new Error('WORKER_CODE_INVALID');
 await pool.query(`insert into private.worker_observations as current_observation(worker,observed_at)
  values($1,clock_timestamp()) on conflict(worker) do update
  set observed_at=greatest(current_observation.observed_at,excluded.observed_at)`,[worker]);
}

/** Check in at startup and at most once per thirty seconds; observation errors never stop queue work. */
export function createWorkerObserver(pool:Pool,worker:WorkerObservationCode,options:WorkerObserverOptions={}):()=>Promise<void>{
 const now=options.now??(()=>performance.now());
 let lastAttemptAt:number|undefined;
 return async()=>{
  try{
   const current=now();
   if(!Number.isFinite(current))throw new Error('WORKER_OBSERVATION_CLOCK_INVALID');
   if(lastAttemptAt!==undefined&&current-lastAttemptAt<30_000)return;
   lastAttemptAt=current;
   await recordWorkerObservation(pool,worker);
  }catch{console.error('WORKER_OBSERVATION_FAILED');}
 };
}
